version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"

  grpc-server:
    build: .
    container_name: grpc-server
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017
    ports:
      - "50051:50051"
    depends_on:
      - mongodb
      - rabbitmq

volumes:
  mongodb_data:
