# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"\x07\n\x05\x45mpty\"W\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05naziv\x18\x02 \x01(\t\x12\x10\n\x08kolicina\x18\x03 \x01(\t\x12\r\n\x05\x65nota\x18\x04 \x01(\t\x12\x10\n\x08lokacija\x18\x05 \x01(\t\"\x17\n\tProductID\x12\n\n\x02id\x18\x01 \x01(\t\"1\n\x0bProductList\x12\"\n\x08products\x18\x01 \x03(\x0b\x32\x10.product.Product2\xe8\x01\n\x0eProductService\x12\x36\n\x0eGetAllProducts\x12\x0e.product.Empty\x1a\x14.product.ProductList\x12\x32\n\nAddProduct\x12\x10.product.Product\x1a\x12.product.ProductID\x12\x33\n\rUpdateProduct\x12\x10.product.Product\x1a\x10.product.Product\x12\x35\n\rDeleteProduct\x12\x12.product.ProductID\x1a\x10.product.Productb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=26
  _EMPTY._serialized_end=33
  _PRODUCT._serialized_start=35
  _PRODUCT._serialized_end=122
  _PRODUCTID._serialized_start=124
  _PRODUCTID._serialized_end=147
  _PRODUCTLIST._serialized_start=149
  _PRODUCTLIST._serialized_end=198
  _PRODUCTSERVICE._serialized_start=201
  _PRODUCTSERVICE._serialized_end=433
# @@protoc_insertion_point(module_scope)
