version: "3.8"

services:
  # mongodb:
  #   image: mongo:latest
  #   container_name: mongodb
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=example
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=admin
  #     - RABBITMQ_DEFAULT_PASS=admin
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"

  # grpc-server:
  #   build: ./qRPCshramba  
  #   container_name: grpc-server
  #   environment:
  #     - MONGO_URI=mongodb://root:example@mongodb:27017
  #   ports:
  #     - "50051:50051"
  #   depends_on:
  #     - mongodb
  #     - rabbitmq
  
  iskanje:
    build: ./iskanje/demo
    container_name: iskanje
    ports:
      - "8081:8081"

  shramba:
    build: ./shramba
    container_name: shramba
    ports:
      - "8080:8080"

  uporabniki:
    build: ./Uporabniki/Uporabniki
    container_name: uporabniki
    ports:
      - "5102:5102"

  gateway:
    build: ./BFF/WebGateway
    container_name: gateway
    ports:
      - "3000:3000"

  frontend:
    build: ../frontend
    container_name: frontend
    ports:
      - "3001:3001"
      
volumes:
  mongodb_data:
