name: Test springboot on Push to Main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: microservices/Iskanje/demo

    - name: Run tests
      run: ./gradlew test
      working-directory: microservices/Iskanje/demo
